version: '3'

services:
  db:
    image: 'mysql:latest'
    ports:
           - "3306:3307"
    environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=achatdb
    volumes:
           - /home/vagrant/mysql:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backend:
    image: 192.168.1.10:8082/repository/islem/tpachat
    container_name: tpachatApp
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - db
      
