version: '3'
services:
  mysqldb:
    container_name: mysql
    image: mysql:8
    volumes:
      - mysqlvolume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
 
  spring_app:
    image: 192.168.100.6:8083/repository/narjess98/tpachat
    container_name: tpachat
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysql
  
  

